#!/usr/bin/env bash

#example of linking: ln -s  ~/dotfiles/.vimrc ~/.vimrc
#note: the symlinked file must exist in the destination folder, but not in the source (the second argument)

echo running install...
